language: node_js
node_js: node

env:
  - LATEST_WKD=true
  - LATEST_WKD=false

before_install:
  - cd $TRAVIS_BUILD_DIR/.. && $TRAVIS_BUILD_DIR/tools/travis/clonewsk.sh
  - cd $TRAVIS_BUILD_DIR && tools/travis/bxsetup.sh
  
install: 
  - npm install
  - if [ "$LATEST_WKD" = "true" ]; then npm link @openwhisk/deploy fi

script: 
   - npm test

notifications:
  email:
    - villard@us.ibm.com