language: node_js
node_js: node
sudo: required

env:
  - LATEST_WSKD=true
  - LATEST_WSKD=false

before_install:
  - cd $TRAVIS_BUILD_DIR/.. && $TRAVIS_BUILD_DIR/tools/travis/clonewsk.sh
  - cd $TRAVIS_BUILD_DIR && tools/travis/bxsetup.sh
  
install: 
  - npm install
  - if [ "$LATEST_WSKD" = "true" ]; then npm link @openwhisk-deploy ; fi

script: 
   - npm test

notifications:
  email:
    - villard@us.ibm.com