language: node_js
node_js: node

before_install:
  - git clone https://github.com/lionelvillard/openwhisk-deploy.git --depth 3
  - cd openwhisk-deploy
  - npm i 
  - npm link


install: 
  - npm install
  - npm link @openwhisk/deploy

script: 
   - npm test

notifications:
  email:
    - villard@us.ibm.com